import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SSG HUB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon1.svg" type="image" sizes="any" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-pretendard text-primary relative flex w-screen flex-col items-center bg-white antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
